# comment
dependencies:
  build:
   - node:10.8.0

# TODO:
#   - "10.8"
#  - "10.7"
#  - "10.6"
#  - "10.5"
#  - "10.4"
#  - "10.3"
#  - "10.2"
#  - "10.1"
#  - "10.0"
#  - "9.11"
#  - "9.10"
#  - "9.9"
#  - "9.8"
#  - "9.7"
#  - "9.6"
#  - "9.5"
#  - "9.4"
#  - "9.3"
#  - "9.2"
#  - "9.1"
#  - "9.0"
#  - 8
#  - 7
#  - 6

build_targets:
  - name: default
  - name: test
    commands:
      # Travis runs this by default
      - npm install
      - npm test

ci:
  builds:
    - name: test
      build_target: test
